# -*- coding: utf-8 -*-
"""A Methodically ALgorithmically Generated Aleatoric Melody (AMALGAM) project, ver 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eiNcvAwcpv4kcx0geS9_55B5yfJERz9a
"""

import re, random
import numpy as np

notes_track   = np.zeros(0)
counter_track = np.zeros(0)
chord_track   = np.zeros(0)

# ======================================================================================
# LOW-LEVEL AUDIO HELPERS
# ======================================================================================

def _ensure_len(buf, end_n):
    if len(buf) < end_n:
        buf = np.append(buf, np.zeros(end_n - len(buf)))
    return buf

# We now generated different notes in different timbre according to its role.
def _synth_tone(pitch, dur_n, sr, timbre="melody"):
    f = 440 * 2 ** ((pitch - 69) / 12)
    theta = 2 * np.pi * f * np.arange(dur_n) / sr

    # For melody, we put its 2nd - 5th harmonics over it for a richer sense with nth harmonic at 1/n weight
    if timbre == "melody":
        note = np.sin(theta)
        for n in range(2, 6):
            note += (1 / n) * np.sin(n * theta)
        note *= np.logspace(0, -2, dur_n)

    # For the chord, we have 1f1 + 0.5f2 + 0.25f3
    elif timbre == "chord":
        note = np.sin(theta)
        note += 0.5 * np.sin(2 * theta)
        note += 0.25 * np.sin(3 * theta)
        note *= np.logspace(0, -1.7, dur_n)

    # For the bass, we have 1.2 Fundamental + 0.25f2
    elif timbre == "bass":
        note = 1.2 * np.sin(theta)
        note += 0.25 * np.sin(2 * theta)
        note *= np.logspace(0, -1.3, dur_n)

    else:
        note = np.sin(theta)
        note *= np.logspace(0, -2, dur_n)

    return note

# We now have to manage 2 different tracks so melodies and chords can be defaulted into their separated tracks.
# Bass notes goes into the Chords track in later implementations by default.
def add_note_to(buffer_name, pitch, start, duration, amp=1.0, timbre=None):
    global notes_track, chord_track

    start_n = int(start * sr)
    dur_n = max(1, int(duration * sr))
    end_n = start_n + dur_n

    if buffer_name == "melody":
        notes_track = _ensure_len(notes_track, end_n)
        buf = notes_track

        if timbre is None:
            timbre = "melody"

    elif buffer_name == "chords":
        chord_track = _ensure_len(chord_track, end_n)
        buf = chord_track

        if timbre is None:
            timbre = "chord"

    else:
        raise ValueError("Bruh in Add Note Function") # Bruh

    # Synthesize
    note = _synth_tone(pitch, dur_n, sr, timbre=timbre)
    note *= amp
    buf[start_n:end_n] += note

    if buffer_name == "melody":
        notes_track = buf
    else:
        chord_track = buf

# ======================================================================================
# THEORY STUFF, PRESERVED FROM VER.2
# ======================================================================================

NOTE_TO_PC = {
    "C":0, "C#":1, "Db":1, "D":2, "D#":3, "Eb":3, "E":4, "F":5,
    "F#":6, "Gb":6, "G":7, "G#":8, "Ab":8, "A":9, "A#":10, "Bb":10, "B":11
}

def pc_to_midi(pc, octave=4):
    return 12 * (octave + 1) + pc

def build_scale(key="C", scale_type="major", octaves=(4, 5)):
    major      = [0, 2, 4, 5, 7, 9, 11]
    nat_minor  = [0, 2, 3, 5, 7, 8, 10]
    harm_minor = [0, 2, 3, 5, 7, 8, 11]
    melo_minor = [0, 2, 3, 5, 7, 9, 11]

    st = scale_type.lower()
    if st == "major":
        base = major
    elif st in ("nat_minor", "natural_minor", "natural"):
        base = nat_minor
    elif st in ("harm_minor", "harmonic_minor", "harmonic"):
        base = harm_minor
    elif st in ("melo_minor", "melodic_minor", "melodic"):
        base = melo_minor
    else:
        raise ValueError("scale_type must be one of: major, nat_minor, harm_minor, melo_minor")

    tonic_pc = NOTE_TO_PC[key]
    out = []
    for octv in octaves:
        for i in base:
            out.append(pc_to_midi((tonic_pc + i) % 12, octv))
    return sorted(out)

def parse_chord_symbol(sym):
    s = sym.strip()
    m = re.match(r"^([A-G])([#b]?)(.*)$", s)

    if not m:
        raise ValueError(f"Bad chord symbol: {sym}")

    root = m.group(1) + m.group(2)
    rest = (m.group(3) or "").strip()

    root_pc = NOTE_TO_PC[root]
    rlow = rest.lower()

    is_maj = False
    is_min = False
    is_dim = False
    is_aug = False
    has_7  = False
    maj7   = False

    if "maj7" in rlow or "ma7" in rlow or "m7+" in rlow or "Δ" in rest or ("m7" in rest and "maj" in rlow):
        is_maj = True
        has_7 = True
        maj7 = True
    elif "maj" in rlow or ("m7" in rest and "Δ" in rest):
        is_maj = True

    if ("min" in rlow) or (rlow.startswith("m") and not rlow.startswith("maj")) or ("-" in rest):
        is_min = True

    if "dim" in rlow or "o" in rest:
        is_dim = True
    if "aug" in rlow or "+" in rest:
        is_aug = True

    if ("7" in rlow) and not maj7:
        has_7 = True

    if is_dim:
        is_maj = is_min = is_aug = False
    if is_aug:
        is_maj = True
        is_min = False

    if not (is_maj or is_min or is_dim or is_aug):
        is_maj = True

    if is_dim:
        triad = [0, 3, 6]
        seventh = 9
    elif is_min:
        triad = [0, 3, 7]
        seventh = 10
    elif is_aug:
        triad = [0, 4, 8]
        seventh = 10
    else:
        triad = [0, 4, 7]
        seventh = 11 if maj7 else 10

    tones = triad[:]
    if has_7 or maj7:
        tones.append(seventh)

    pcs = [(root_pc + i) % 12 for i in tones]
    return root_pc, pcs

def chord_midi_tones(sym, octaves=(4, 5), include_upper_color=True):
    root_pc, pcs = parse_chord_symbol(sym)

    out = []
    for octv in octaves:
        for pc in pcs:
            out.append(pc_to_midi(pc, octv))

    if include_upper_color:
        for add_int in [2, 5, 9]:
            pc = (root_pc + add_int) % 12
            out.append(pc_to_midi(pc, octaves[-1]))

    return sorted(set(out))

def chord_pitch_classes(sym, include_upper_color=False):
    _, pcs = parse_chord_symbol(sym)
    out = set(pcs)
    if include_upper_color:
        root_pc, _ = parse_chord_symbol(sym)
        for add_int in [2, 5, 9]:
            out.add((root_pc + add_int) % 12)
    return out

# ======================================================================================
# VOICE WEIGHTING FUNCTIONS
# ======================================================================================

# Revised Weighted Selection
# The weight of selecting each note is now 1/(1 + Distance) for each note based on its distance away from the center (default C5)
def weighted_choice(pitches, center=72):
    if not pitches:
        raise ValueError("weighted_choice called with empty pitches")

    weights = [1.0 / (1.0 + abs(p - center)) for p in pitches]
    total = sum(weights)
    r = random.random() * total
    acc = 0.0

    for p, w in zip(pitches, weights):
        acc += w
        if acc >= r:
            return p
    return random.choice(pitches)

# Preserved from Ver. 2
def no_big_leap(prev_pitch, candidate_pitch, allowed_pool, max_leap=7):
    if prev_pitch is None:
        return candidate_pitch
    if abs(candidate_pitch - prev_pitch) <= max_leap:
        return candidate_pitch
    close = [p for p in allowed_pool if abs(p - prev_pitch) <= max_leap]
    return random.choice(close) if close else candidate_pitch

# Searching helpers
def nearest_pitch_with_pc(pc, register_center=72, search_low=48, search_high=96):
    candidates = [p for p in range(search_low, search_high + 1) if (p % 12) == pc]
    return min(candidates, key=lambda p: abs(p - register_center))

def nearest_from_pool(pool, target):
    return min(pool, key=lambda p: abs(p - target))

def in_range(pool, low, high):
    return [p for p in pool if low <= p <= high]

# Instead of doing a fixed chord for each chord progression input,
# we now try to find the smoothest voice leading possible by having each note moves to the nearest chord independently.
# TODO: Right now, certain progression MAY cause overlapping voices that puts two voices on the exact same note! >>>>>>>>>>>>>>>>>>>>>>>>>>
def smooth_voicing(tones, prev_voicing=None, desired_size=4):
    tones = sorted(tones)
    if len(tones) >= desired_size:
        base = tones[:desired_size]
    else:
        base = tones[:]
        while len(base) < desired_size:
            base.append(base[-1] + 12)

    if prev_voicing is None:
        return base

    voiced = []
    for i, p in enumerate(base):
        target = prev_voicing[min(i, len(prev_voicing) - 1)]
        cands = [p - 12, p, p + 12, p + 24]
        best = min(cands, key=lambda x: abs(x - target))
        voiced.append(best)

    # Sorting prevents crossing, but does not currently prevents overlapping voices.
    voiced = sorted(voiced)
    return voiced

# ======================================================================================
# RHYTHM VARIATION FUNCTIONS
# ======================================================================================

def metric_role(tick, ticks_per_beat=4, beats_per_bar=4):
    ticks_per_bar = ticks_per_beat * beats_per_bar
    pos = tick % ticks_per_bar

    if pos == 0:
        return "bar_downbeat"      # beat 1
    elif pos == 2 * ticks_per_beat:
        return "midbar_strong"     # beat 3
    elif pos % ticks_per_beat == 0:
        return "beat"              # beats 2 and 4
    else:
        return "offbeat"

def choose_phrase_contour(): # Phrase contours for random choice
    return random.choice(["up", "down", "arch", "wave"])

# Predefine some rhythm cells in order for the melody to sound more rooted
RHYTHM_CELLS = [
    [4, 4, 4, 4],
    [8, 4, 4],
    [4, 2, 2, 4, 4],
    [2, 2, 4, 2, 2, 4],
    [6, 2, 4, 4],
    [4, 4, 2, 2, 4],
    [2, 2, 2, 2, 4, 4],
    [4, 2, 2, 2, 2, 4],
]

# In melodic expression density with less than 0.7 we only apply the calm ones
def choose_rhythm_cell(activity=0.5):
    if activity < 0.3:
        choices = RHYTHM_CELLS[:3]
    elif activity < 0.7:
        choices = RHYTHM_CELLS[:8]
    else:
        choices = RHYTHM_CELLS
    return random.choice(choices)

# Do a redivision of bars based on the rhythm cells we had
def fill_bar_with_cells(bar_ticks, activity=0.5):
    out = []
    remaining = bar_ticks

    while remaining > 0:
        cell = choose_rhythm_cell(activity=activity)
        total = sum(cell)

        if total <= remaining:
            out.extend(cell)
            remaining -= total
        else:
            # fallback: fill remaining more conservatively
            if remaining in (1, 2, 3, 4, 6, 8):
                out.append(remaining)
            else:
                out.append(4)
                remaining -= 4
                continue
            remaining = 0

    return out

# ======================================================================================
# MELODIC GRAMMAR FUNCTIONS
# ======================================================================================

# Preserved from Ver. 2
def melodic_minor_adjust(pool, key="C", prev_pitch=None, max_leap=7):
    tonic_pc = NOTE_TO_PC[key]
    nat6_pc = (tonic_pc + 8) % 12
    nat7_pc = (tonic_pc + 10) % 12

    adjusted = []
    for p in pool:
        if (p % 12) == nat6_pc and prev_pitch is not None and p > prev_pitch and abs((p + 1) - prev_pitch) <= max_leap:
            adjusted.append(p + 1)
        elif (p % 12) == nat7_pc and prev_pitch is not None and p > prev_pitch and abs((p + 1) - prev_pitch) <= max_leap:
            adjusted.append(p + 1)
        else:
            adjusted.append(p)
    return sorted(set(adjusted))

# Define a dynamic pool of usable beats according to the roles for each note
def choose_pool_by_metric(role, chord_tones, scale_tones, next_chord_tones=None):
    chord_pcs = {p % 12 for p in chord_tones}
    nonchord = [p for p in scale_tones if (p % 12) not in chord_pcs]

    if next_chord_tones is None:
        next_chord_tones = []

    # Define an anticipation zone that allows the melody to be generated based on the NEXT chord progression
    next_chord_pcs = {n % 12 for n in next_chord_tones}
    anticipation = [
        p for p in scale_tones
        if (p % 12) in next_chord_pcs
        and (p % 12) not in chord_pcs
    ]

    # Probability patterns, self explanatory
    if role == "bar_downbeat":
        pool = chord_tones * 10 + nonchord * 1
    elif role == "midbar_strong":
        pool = chord_tones * 7 + nonchord * 2
    elif role == "beat":
        pool = chord_tones * 4 + nonchord * 3
    else:
        pool = chord_tones * 2 + nonchord * 5 + anticipation * 2

    return pool

# The Contour Filter endows a Multiplication process to all notes that fit the desired contour.
# e.g. if you are on 67 and have [64, 65, 68] in the pool with an "UP" contour,
# The code multiplies the 68 by 3 and output [64, 65, 68, 68, 68].
# Similarly, a "DOWN" contour would give [64, 64, 64, 65, 65, 65, 68]
def contour_filter(candidates, prev_pitch, contour, bar_progress):
    if prev_pitch is None:
        return candidates

    if contour == "up":
        weighted = candidates + [p for p in candidates if p >= prev_pitch] * 3

    elif contour == "down":
        weighted = candidates + [p for p in candidates if p <= prev_pitch] * 3

    # TODO: Do a smart filter on convex and concave arch - previously tried, unsuccessful so cut out of the code >>>>>>>>>>>>>>>>>>>>>>>>>>
    elif contour == "arch":
        if bar_progress < 0.5:
            weighted = candidates + [p for p in candidates if p >= prev_pitch] * 2
        else:
            weighted = candidates + [p for p in candidates if p <= prev_pitch] * 2

    elif contour == "wave":
        if int(bar_progress * 4) % 2 == 0:
            weighted = candidates + [p for p in candidates if p >= prev_pitch] * 2
        else:
            weighted = candidates + [p for p in candidates if p <= prev_pitch] * 2

    else:
        weighted = candidates

    return weighted if weighted else candidates


# If an interval of 3rd, 4th or 5th would be produced, consider invoking the function and smoothen it out by inserting an arith avg note in between
def choose_stepwise_nonchord(prev_pitch, target_pitch, scale_pool):

    low = min(prev_pitch, target_pitch)
    high = max(prev_pitch, target_pitch)

    between = [p for p in scale_pool if low < p < high]

    if abs(target_pitch - prev_pitch) in (3, 4, 5) and between:
        return weighted_choice(between, center=(prev_pitch + target_pitch) / 2)

    neighbors = [p for p in scale_pool if abs(p - prev_pitch) in (1, 2)]
    if neighbors:
        return random.choice(neighbors)

    return target_pitch

# ======================================================================================
# ACCOMPANIMENT GENERATION
# ======================================================================================


# Preserved from Ver. 2
def _build_progression_blocks(progression):
    blocks = []
    s = 0
    for sym, L in progression:
        blocks.append((sym, L, s))
        s += L
    return blocks

def chord_at_tick(blocks, tick):
    for i, (sym, L, start) in enumerate(blocks):
        if start <= tick < start + L:
            next_sym = blocks[(i + 1) % len(blocks)][0]
            return sym, L, start, next_sym
    sym, L, start = blocks[-1]
    return sym, L, start, blocks[0][0]

# This improved entire chunk is responsible for generating the underlying chords.
# There are currently Blocks, Bass Chords, Arpeggio and Waltz available.
def generate_chord_background(progression, bpm=200, ticks_per_beat=4,
                              chord_octaves=(3, 4), chord_amp=0.18,
                              style="arpeggio"):
    global chord_track
    chord_track = np.zeros(0)

    beat_sec = 60.0 / bpm
    tick_sec = beat_sec / ticks_per_beat

    now = 0.0
    prev_voicing = None

    # Process chords
    for sym, L in progression:
        tones = chord_midi_tones(sym, octaves=chord_octaves, include_upper_color=False)
        tones = sorted(tones)
        dur_sec = L * tick_sec

        if style == "block": # Block chords
            voicing = smooth_voicing(tones, prev_voicing=prev_voicing, desired_size=4)
            for p in voicing:
                add_note_to("chords", p, now, dur_sec, amp=chord_amp, timbre="chord")
            prev_voicing = voicing

        elif style == "bass_chord": # Bass chords
            ticks_left = L
            t = 0
            voicing = smooth_voicing(tones, prev_voicing=prev_voicing, desired_size=4)
            bass = min(voicing)
            upper = voicing[1:]

            while ticks_left > 0:
                step = min(ticks_per_beat, ticks_left)
                # Have the bass ends before the next one begins for better effect
                add_note_to("chords", bass, now + t * tick_sec, step * tick_sec * 0.95, amp=chord_amp * 1.15, timbre="bass")

                # Have a stab kick in at 0.48 interval (which sounds better than 0.5)
                stab_start = now + t * tick_sec + (step * tick_sec) * 0.48
                stab_dur   = max(0.04, step * tick_sec * 0.35)
                for p in upper:
                    add_note_to("chords", p, stab_start, stab_dur, amp=chord_amp * 0.75, timbre="chord")

                t += step
                ticks_left -= step

            prev_voicing = voicing

        elif style == "arpeggio": # Arpeggios
            voicing = smooth_voicing(tones, prev_voicing=prev_voicing, desired_size=4)
            pattern_idx = [0, 1, 2, 1, 3, 2, 1, 2] # Alterable! Currently something like C1 - E - G - E - C2 - E - G - E
            for i in range(L):
                p = voicing[pattern_idx[i % len(pattern_idx)]]
                # Again, have the note end a little bit earlier for better effect
                add_note_to("chords", p, now + i * tick_sec, tick_sec * 0.95, amp=chord_amp, timbre="chord")
            prev_voicing = voicing

        elif style == "waltz": # DUM - ba - ba - DUM - ba - ba
            voicing = smooth_voicing(tones, prev_voicing=prev_voicing, desired_size=4)
            bass = min(voicing)
            upper = voicing[1:]
            for i in range(L):
                if i % ticks_per_beat == 0:
                    add_note_to("chords", bass, now + i * tick_sec, tick_sec * 0.95, amp=chord_amp * 1.2, timbre="bass")
                else:
                    for p in upper:
                        add_note_to("chords", p, now + i * tick_sec, tick_sec * 0.8, amp=chord_amp * 0.7, timbre="chord")
            prev_voicing = voicing

        else:
            raise ValueError("Bruh") # Bruh

        now += dur_sec

    return now

# ======================================================================================
# END PHASE FUNCTIONS
# ======================================================================================

def _ending_durations(remaining_ticks):
    if remaining_ticks <= 1:
        return [remaining_ticks]

    if remaining_ticks == 2:
        return [1, 1]

    if remaining_ticks == 3:
        return [1, 1, 1]

    # Rough shape: 1/4, 1/8, 1/8, 1/2
    d1 = max(1, remaining_ticks // 4)
    d2 = max(1, remaining_ticks // 8)
    d3 = max(1, remaining_ticks // 8)
    d4 = remaining_ticks - d1 - d2 - d3

    # Make sure the final duration is at least 1
    while d4 < 1:
        if d3 > 1:
            d3 -= 1
        elif d2 > 1:
            d2 -= 1
        elif d1 > 1:
            d1 -= 1
        d4 = remaining_ticks - d1 - d2 - d3

    return [d1, d2, d3, d4]


def _ending_sentence_pitches(key="C", scale_type="major", prev_pitch=None, center_pitch=72):
    tonic_pc = NOTE_TO_PC[key]
    dominant_pc = (tonic_pc + 7) % 12
    supertonic_pc = (tonic_pc + 2) % 12

    st = scale_type.lower()
    if st in ("nat_minor", "natural_minor", "natural"):
        lead_pc = (tonic_pc + 10) % 12   # b7
    else:
        lead_pc = (tonic_pc + 11) % 12   # leading tone

    # Pick a simple cadential pattern
    if st in ("nat_minor", "natural_minor", "natural"):
        pcs = [dominant_pc, lead_pc, supertonic_pc, tonic_pc]
    else:
        pcs = [dominant_pc, supertonic_pc, lead_pc, tonic_pc]

    pitches = []
    target = prev_pitch if prev_pitch is not None else center_pitch

    for i, pc in enumerate(pcs):
        p = nearest_pitch_with_pc(pc, register_center=target, search_low=60, search_high=84)

        # Try to keep it reasonably singable / connected
        if pitches:
            while p - pitches[-1] > 7 and p - 12 >= 60:
                p -= 12
            while pitches[-1] - p > 7 and p + 12 <= 84:
                p += 12

        pitches.append(p)
        target = p

    # Force the very last note to be a tonic near the center,
    # so it feels final and stable
    pitches[-1] = nearest_pitch_with_pc(tonic_pc, register_center=center_pitch, search_low=60, search_high=84)

    return pitches


def add_ending_sentence(start_time, remaining_ticks, tick_sec,
                        key="C", scale_type="major",
                        prev_pitch=None, center_pitch=72):
    """
    Writes a fixed cadential ending into the melody track.
    """
    durs = _ending_durations(remaining_ticks)
    pitches = _ending_sentence_pitches(
        key=key,
        scale_type=scale_type,
        prev_pitch=prev_pitch,
        center_pitch=center_pitch
    )

    t = start_time
    last_pitch = prev_pitch

    # If we have fewer durations than 4 because remaining_ticks is tiny,
    # just use the tail of the cadence.
    pitches = pitches[-len(durs):]

    for i, (p, dur) in enumerate(zip(pitches, durs)):
        # Slight emphasis on the final note
        amp = 1.15 if i == len(durs) - 1 else 1.0
        add_note_to("melody", p, t, dur * tick_sec, amp=amp, timbre="melody")
        t += dur * tick_sec
        last_pitch = p

    return last_pitch

# ======================================================================================
# MELODY GENERATION
# ======================================================================================

def generate_melody(progression, bpm=200, ticks_per_beat=4, beats_per_bar=4,
                    key="C", scale_type="major",
                    rest_prob=0.08, max_leap=7, center_pitch=72,
                    activity=0.60, ending_bars=1):
    global notes_track
    notes_track = np.zeros(0)

    beat_sec = 60.0 / bpm
    tick_sec = beat_sec / ticks_per_beat

    total_ticks = sum(L for _, L in progression)
    total_time = total_ticks * tick_sec
    blocks = _build_progression_blocks(progression)

    scale_main = build_scale(key=key, scale_type=scale_type, octaves=(4, 5))
    scale_nat  = build_scale(key=key, scale_type="nat_minor", octaves=(4, 5))

    tick = 0
    now = 0.0
    prev_pitch = None
    ending_ticks = ticks_per_beat * beats_per_bar * ending_bars

    while tick < total_ticks:
        remaining_ticks = total_ticks - tick

        # End phase logistics
        if remaining_ticks <= ending_ticks:
            prev_pitch = add_ending_sentence(
                start_time=now,
                remaining_ticks=remaining_ticks,
                tick_sec=tick_sec,
                key=key,
                scale_type=scale_type,
                prev_pitch=prev_pitch,
                center_pitch=center_pitch
            )
            break
        bar_ticks = min(ticks_per_beat * beats_per_bar, total_ticks - tick)
        contour = choose_phrase_contour()
        rhythm = fill_bar_with_cells(bar_ticks, activity=activity)

        local_tick = 0

        # Run the CT/NCT filter for each "bar" predefined in the rhythm pattern
        for dur in rhythm:
            if tick >= total_ticks:
                break

            curr_sym, _, chord_start, next_sym = chord_at_tick(blocks, tick)
            role = metric_role(tick, ticks_per_beat=ticks_per_beat, beats_per_bar=beats_per_bar)


            # We now generate every CT along with the NEXT CT before filling in the NCT in between for better phrase accomodation
            chord_tones_strong = chord_midi_tones(curr_sym, octaves=(4, 5), include_upper_color=False)
            chord_tones_weak   = chord_midi_tones(curr_sym, octaves=(4, 5), include_upper_color=True)
            next_chord_tones   = chord_midi_tones(next_sym, octaves=(4, 5), include_upper_color=False)

            # Better 6th and 7th raise checks for Melodic Minor now based on the movements
            if scale_type.lower() in ("melo_minor", "melodic_minor", "melodic"):
                scale_pool = melodic_minor_adjust(scale_nat + chord_tones_weak, key=key, prev_pitch=prev_pitch, max_leap=max_leap)
            else:
                scale_pool = sorted(set(scale_main + chord_tones_weak))

            cycle_pos = tick
            boundary_cut = None
            for sym2, L2, start2 in blocks:
                db = start2
                if tick < db < tick + dur: # We preserve the logic that avoids generation from passing through a strong beat
                    boundary_cut = db - tick
                    break
            if boundary_cut is not None and boundary_cut > 0:
                dur = boundary_cut

            bar_progress = local_tick / max(1, bar_ticks)

            # Optional rest can now occur on weaker positions only
            if role in ("beat", "offbeat") and random.random() < rest_prob: # The default is now 8%
                tick += dur
                now += dur * tick_sec
                local_tick += dur
                continue

            pool = choose_pool_by_metric(role, chord_tones_strong, scale_pool, next_chord_tones=next_chord_tones)
            pool = in_range(pool, 60, 84) # 72 +- 12

            if not pool:
                pool = chord_tones_strong[:]

            pool = contour_filter(pool, prev_pitch, contour, bar_progress)

            if role in ("bar_downbeat", "midbar_strong"): # Strong position
                cand = weighted_choice(pool, center=center_pitch)
                cand = no_big_leap(prev_pitch, cand, pool, max_leap=max_leap)

            elif role == "beat":
                base = weighted_choice(pool, center=center_pitch)
                base = no_big_leap(prev_pitch, base, pool, max_leap=max_leap)
                cand = base

            else:  # offbeat
                target_pool = in_range(next_chord_tones + chord_tones_strong, 60, 84) # Offbeat - Onbeat should bias toward smooth motion
                if target_pool:
                    target = weighted_choice(target_pool, center=center_pitch)
                else:
                    target = weighted_choice(chord_tones_strong, center=center_pitch)

                if prev_pitch is not None and random.random() < 0.65: # Alterable - Feel free to change. Currently 65% of the time the algorithm favors smooth steps
                    cand = choose_stepwise_nonchord(prev_pitch, target, scale_pool) # Focus on smooth motion
                else:
                    cand = weighted_choice(pool, center=center_pitch)

                cand = no_big_leap(prev_pitch, cand, pool, max_leap=max_leap)

            add_note_to("melody", cand, now, dur * tick_sec, amp=1.0, timbre="melody")
            prev_pitch = cand
            tick += dur
            now += dur * tick_sec
            local_tick += dur

    return total_time


# ======================================================================================
# TRACK MIXING AND PLAY FUNCTIONS
# ======================================================================================

def mix_tracks(melody_gain=0.85, counter_gain=0.55, chord_gain=0.60):
    max_len = max(len(notes_track), len(counter_track), len(chord_track), 1)

    mel = _ensure_len(notes_track.copy(), max_len) if len(notes_track) else np.zeros(max_len)
    ctr = _ensure_len(counter_track.copy(), max_len) if len(counter_track) else np.zeros(max_len)
    chd = _ensure_len(chord_track.copy(), max_len) if len(chord_track) else np.zeros(max_len)

    mix = melody_gain * mel + counter_gain * ctr + chord_gain * chd

    peak = np.max(np.abs(mix))
    if peak > 0.98:
        mix = 0.98 * mix / peak

    return mix

def sound(buffer, sr, name=None):
    buffer = np.asarray(buffer)

    if buffer.ndim == 2 and buffer.shape[0] == 2 and buffer.shape[1] != 2:
        buffer = buffer.T

    if buffer.ndim == 1:
        pass
    elif buffer.ndim == 2 and buffer.shape[1] == 2:
        pass
    else:
        raise ValueError("Buffer must be mono or stereo with shape (n,) or (n,2)")

    buffer = np.clip(buffer, -1.0, 1.0)
    display(Audio(buffer, rate=sr))

# C Major, Arpeggio

from IPython.display import Audio, display
import numpy as np

# =======================
# SAMPLE RATE
# =======================
sr = 44100

# =======================
# CHORD PROGRESSION
# =======================
progression = [
    ("Am", 8), ("Am", 8),
    ("Am", 8), ("Am", 8),
    ("F", 8), ("F", 8),
    ("F", 8), ("F", 8),
    ("C", 8), ("C", 8),
    ("C", 8), ("C", 8),
    ("G", 8), ("G", 8),
    ("G", 8), ("G", 8),
    ("C", 16)
] # Alterable

# =======================
# GENERATE LAYERS SEPARATELY
# =======================
generate_chord_background(
    progression=progression,
    bpm=90, # Alterable
    ticks_per_beat=4, # Alterable
    chord_octaves=(4, 5), # Alterable
    chord_amp=0.32, # Alterable
    style="arpeggio" # Choose from block, bass_chord, arpeggio or waltz
)

generate_melody(
    progression=progression,
    bpm=90, # Alterable
    ticks_per_beat=4, # Alterable
    beats_per_bar=4, # Alterable
    key="C", # Alterable
    scale_type="major", # Choose from major, nat_minor, harm_minor or melo_minor
    rest_prob=0.07,
    max_leap=7,
    center_pitch=72, # C5
    activity=0.6 # Biased note generation variability
)

# =======================
# MIX WITH STRONGER CHORDS
# =======================
piece = mix_tracks(
    melody_gain=0.75,
    counter_gain=0.0,
    chord_gain=1.0
)

# =======================
# PLAY AUDIO
# =======================
sound(piece, sr)

# C Major, Bass Chord

from IPython.display import Audio, display
import numpy as np

# =======================
# SAMPLE RATE
# =======================
sr = 44100

# =======================
# CHORD PROGRESSION
# =======================
progression = [
    ("Am", 8), ("Am", 8),
    ("Am", 8), ("Am", 8),
    ("F", 8), ("F", 8),
    ("F", 8), ("F", 8),
    ("C", 8), ("C", 8),
    ("C", 8), ("C", 8),
    ("G", 8), ("G", 8),
    ("G", 8), ("G", 8),
    ("C", 16)
] # Alterable

# =======================
# GENERATE LAYERS SEPARATELY
# =======================
generate_chord_background(
    progression=progression,
    bpm=90, # Alterable
    ticks_per_beat=4, # Alterable
    chord_octaves=(4, 5), # Alterable
    chord_amp=0.32, # Alterable
    style="bass_chord" # Choose from block, bass_chord, arpeggio or waltz
)

generate_melody(
    progression=progression,
    bpm=90, # Alterable
    ticks_per_beat=4, # Alterable
    beats_per_bar=4, # Alterable
    key="C", # Alterable
    scale_type="major", # Choose from major, nat_minor, harm_minor or melo_minor
    rest_prob=0.07,
    max_leap=7,
    center_pitch=72, # C5
    activity=0.6 # Biased note generation variability
)

# =======================
# MIX WITH STRONGER CHORDS
# =======================
piece = mix_tracks(
    melody_gain=0.75,
    counter_gain=0.0,
    chord_gain=1.0
)

# =======================
# PLAY AUDIO
# =======================
sound(piece, sr)

# A Natural Minor, Arpeggio

from IPython.display import Audio, display
import numpy as np

# =======================
# SAMPLE RATE
# =======================
sr = 44100

# =======================
# CHORD PROGRESSION
# =======================
progression = [
    ("Am", 8), ("Am", 8),
    ("Am", 8), ("Am", 8),
    ("F", 8), ("F", 8),
    ("F", 8), ("F", 8),
    ("C", 8), ("C", 8),
    ("C", 8), ("C", 8),
    ("G", 8), ("G", 8),
    ("G", 8), ("G", 8),
    ("Am", 16)
] # Alterable

# =======================
# GENERATE LAYERS SEPARATELY
# =======================
generate_chord_background(
    progression=progression,
    bpm=90, # Alterable
    ticks_per_beat=4, # Alterable
    chord_octaves=(4, 5), # Alterable
    chord_amp=0.32, # Alterable
    style="arpeggio" # Choose from block, bass_chord, arpeggio or waltz
)

generate_melody(
    progression=progression,
    bpm=90, # Alterable
    ticks_per_beat=4, # Alterable
    beats_per_bar=4, # Alterable
    key="A", # Alterable
    scale_type="nat_minor", # Choose from major, nat_minor, harm_minor or melo_minor
    rest_prob=0.07,
    max_leap=7,
    center_pitch=72, # C5
    activity=0.6 # Biased note generation variability
)

# =======================
# MIX WITH STRONGER CHORDS
# =======================
piece = mix_tracks(
    melody_gain=0.75,
    counter_gain=0.0,
    chord_gain=1.0
)

# =======================
# PLAY AUDIO
# =======================
sound(piece, sr)

# A Melodic Minor, Arpeggio

from IPython.display import Audio, display
import numpy as np

# =======================
# SAMPLE RATE
# =======================
sr = 44100

# =======================
# CHORD PROGRESSION
# =======================
progression = [
    ("Am", 8), ("Am", 8),
    ("Am", 8), ("Am", 8),
    ("F", 8), ("F", 8),
    ("F", 8), ("F", 8),
    ("C", 8), ("C", 8),
    ("C", 8), ("C", 8),
    ("G", 8), ("G", 8),
    ("G", 8), ("G", 8),
    ("Am", 16)
] # Alterable

# =======================
# GENERATE LAYERS SEPARATELY
# =======================
generate_chord_background(
    progression=progression,
    bpm=90, # Alterable
    ticks_per_beat=4, # Alterable
    chord_octaves=(4, 5), # Alterable
    chord_amp=0.32, # Alterable
    style="arpeggio" # Choose from block, bass_chord, arpeggio or waltz
)

generate_melody(
    progression=progression,
    bpm=90, # Alterable
    ticks_per_beat=4, # Alterable
    beats_per_bar=4, # Alterable
    key="A", # Alterable
    scale_type="melo_minor", # Choose from major, nat_minor, harm_minor or melo_minor
    rest_prob=0.07,
    max_leap=7,
    center_pitch=72, # C5
    activity=0.6 # Biased note generation variability
)

# =======================
# MIX WITH STRONGER CHORDS
# =======================
piece = mix_tracks(
    melody_gain=0.75,
    counter_gain=0.0,
    chord_gain=1.0
)

# =======================
# PLAY AUDIO
# =======================
sound(piece, sr)

# C Major, Bass Chord

from IPython.display import Audio, display
import numpy as np

# =======================
# SAMPLE RATE
# =======================
sr = 44100

# =======================
# CHORD PROGRESSION
# =======================
progression = [
    ("Am", 8), ("Am", 8),
    ("Am", 8), ("Am", 8),
    ("F", 8), ("F", 8),
    ("F", 8), ("F", 8),
    ("C", 8), ("C", 8),
    ("C", 8), ("C", 8),
    ("G", 8), ("G", 8),
    ("G", 8), ("G", 8),
    ("C", 16)
] # Alterable

# =======================
# GENERATE LAYERS SEPARATELY
# =======================
generate_chord_background(
    progression=progression,
    bpm=90, # Alterable
    ticks_per_beat=4, # Alterable
    chord_octaves=(4, 5), # Alterable
    chord_amp=0.32, # Alterable
    style="bass_chord" # Choose from block, bass_chord, arpeggio or waltz
)

generate_melody(
    progression=progression,
    bpm=90, # Alterable
    ticks_per_beat=4, # Alterable
    beats_per_bar=4, # Alterable
    key="C", # Alterable
    scale_type="major", # Choose from major, nat_minor, harm_minor or melo_minor
    rest_prob=0.07,
    max_leap=7,
    center_pitch=72, # C5
    activity=0.6 # Biased note generation variability
)

# =======================
# MIX WITH STRONGER CHORDS
# =======================
piece = mix_tracks(
    melody_gain=0.75,
    counter_gain=0.0,
    chord_gain=1.0
)

# =======================
# PLAY AUDIO
# =======================
sound(piece, sr)

# A Natural Minor, Waltz

from IPython.display import Audio, display
import numpy as np

# =======================
# SAMPLE RATE
# =======================
sr = 44100

# =======================
# CHORD PROGRESSION
# =======================
progression = [
    ("Am", 6), ("Am", 6),
    ("Am", 6), ("Am", 6),
    ("F", 6), ("F", 6),
    ("F", 6), ("F", 6),
    ("C", 6), ("C", 6),
    ("C", 6), ("C", 6),
    ("G", 6), ("G", 6),
    ("G", 6), ("G", 6),
    ("Am", 12)
] # Alterable

# =======================
# GENERATE LAYERS SEPARATELY
# =======================
generate_chord_background(
    progression=progression,
    bpm=60, # Alterable
    ticks_per_beat=3, # Alterable
    chord_octaves=(4, 5), # Alterable
    chord_amp=0.32, # Alterable
    style="waltz" # Choose from block, bass_chord, arpeggio or waltz
)

generate_melody(
    progression=progression,
    bpm=60, # Alterable
    ticks_per_beat=3, # Alterable
    beats_per_bar=3, # Alterable
    key="A", # Alterable
    scale_type="nat_minor", # Choose from major, nat_minor, harm_minor or melo_minor
    rest_prob=0.07,
    max_leap=7,
    center_pitch=72, # C5
    activity=0.8 # Biased note generation variability
)

# =======================
# MIX WITH STRONGER CHORDS
# =======================
piece = mix_tracks(
    melody_gain=0.75,
    counter_gain=0.0,
    chord_gain=1.0
)

# =======================
# PLAY AUDIO
# =======================
sound(piece, sr)

# Testing block, not coding relevant
print(chord_track.shape, notes_track.shape)